url: https://theavila.github.io/

# Site settings
title: "Aprendizagem de Máquina e Ciência de Dados"
email: ricardo.lims@gmail.com
description: "Aprendizagem de Máquina"


# Team names, titles and social links
people:
- name: Ricardo Ávila
  pic: 1
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/theavila
  - title: github
    url: https://github.com/theavila

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
