url: https://theavila.github.io/

# Site settings
title: "Aprendizagem de Máquina e Ciência de Dados"
email: ricardo.lims@gmail.com
description: "Aprendizagem de Máquina"


# Team names, titles and social links
people:
- name: Ricardo Ávila
  pic: 1
  social:
    - title: twitter
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/theavila
  - title: github
    url: https://github.com/theavila
  - title: linkedin
    url: https://www.linkedin.com/in/theavila
  - title: bitbucket
    url: https://bitbucket.org/theavila/
  - title: graduation-cap
    url: https://scholar.google.pt/citations?user=3bMNkzYAAAAJ&hl=pt-PT
#  - title: medium
#    url: https://medium.com/@theavila
#  - name: stack-overflow
#    url: https://stackoverflow.com/users/10060380/theavila

# Postal address (add as many lines as necessary)
address:
  - line: Évora, PT

footer:
  copyright: Me. Ricardo Ávila
  location: Reino de Deus
  social: Passageiro nesse mundo
  credits: Credits

# Credits content
credits: 'Site atualizado semanalmente. Atrasos podem ocorrer.'

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
